<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart\Grid */
?>

<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= /* @escapeNotVerified */ $block->getUrl('checkout/cart/updatePost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'
          class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
	<div class="cart-content">
		<div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
			<?php if ($block->getPagerHtml()): ?>
				<div class="cart-products-toolbar cart-products-toolbar-top toolbar" data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?></div>
			<?php endif ?>
			<table id="shopping-cart-table"
				   class="cart items data table"
				   data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
				   "updateCartActionContainer": "#update_cart_action_container"}}'>
				<caption role="heading" aria-level="2" class="table-caption"><?= /* @escapeNotVerified */ __('Shopping Cart Items') ?></caption>
				<thead>
					<tr>
						<th class="col item" scope="col"><span><?= /* @escapeNotVerified */ __('Product') ?></span></th>
						<th class="col text-center" scope="col"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></th>
						<th class="col text-center" scope="col"><span><?= /* @escapeNotVerified */ __('Price') ?></span></th>
						<!--<th class="col subtotal" scope="col"><span><?=  __('Subtotal') ?></span></th> -->
						<th class="col action" scope="col">&nbsp;</th>
					</tr>
				</thead>
				<?php foreach ($block->getItems() as $_item): ?>
					<?= $block->getItemHtml($_item) ?>
				<?php endforeach ?>
			</table>
			<?php if ($block->getPagerHtml()): ?>
				<div class="cart-products-toolbar cart-products-toolbar-bottom toolbar" data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?></div>
			<?php endif ?>

            <?php
            // @codingStandardsIgnoreFile
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $crossellProduct = $objectManager->get('Infortis\Base\Helper\Data')->getExtrasProduct();
            $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
            if(count($crossellProduct)):
            ?>
            <div id="extrasbox" class="opc-block-summary opc-block-extras" style="background-color: inherit">
                <span class="title" style="border-bottom: inherit;">ADD EXTRAS TO THIS BOX</span>
                <p>Please Note: You may only include 1 bottle of wine or juice per box.</p>
                <div class="block items-in-cart" >
                    <div class="content minicart-items">
                        <div class="minicart-items-wrapper overflowed">
                            <ol class="row minicart-items">
                                <?php foreach($crossellProduct as $crossell): ?>
                                    <li class="col-md-4 col-sm-6" data-id="<?php echo $crossell["entity_id"] ?>">
                                        <div class="caddie-extra" style="display: flex">
                                            <div>
                                                <p>
                                                    <img src="<?php echo $crossell["thumbnail"] ?>" alt="<?php echo $crossell["name"] ?>">
                                                </p>
                                            </div>
                                            <div style="margin-left: 15px">
                                                <span class="package-item-title"><?php echo $crossell["name"] ?></span>
                                                <div class="caddie-extra-cart">
                                                    <div class="caddie-extra-cart-item extra-item"><input type="input" name="item-qty" value="<?php echo $crossell["qtyQuote"] ?>" id="item_<?php echo $crossell["entity_id"] ?>"></div>
                                                    <div class="caddie-extra-cart-item btn-group">
                                                        <button type="button" class="item-button decrease"><i class="fa fa-minus"></i></button>
                                                        <button type="button" class="item-button increase"><i class="fa fa-plus"></i></button>
                                                    </div>
                                                    <div class="caddie-extra-cart-item caddie-extra-price">
                                                        <span class="subtotal"><?php echo array_key_exists('special_price',$crossell) ? $priceHelper->currency($crossell["special_price"], true, false) : $priceHelper->currency($crossell["price"], true, false) ?></span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                <?php endforeach; ?>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
    <div class="cart main actions">
		<!--
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                class="action clear" id="empty_cart_button">
            <span><?= /* @escapeNotVerified */ __('Clear Shopping Cart') ?></span>
        </button>
		-->
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="button action"
               href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
                <span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span>
            </a>
        <?php endif; ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $block->escapeHtml(__('Update My Changes')) ?>"
                class="action active">
            <span><?= /* @escapeNotVerified */ __('Update My Changes') ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
<!--	--><?php //
//		// @codingStandardsIgnoreFile
//		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//		$crossellProduct = $objectManager->get('Infortis\Base\Helper\Data')->getExtrasProduct();
//		$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
//		if(count($crossellProduct)):
//	?>
</form>
<div class="clearer"></div>
<!--<div id="extrasbox" class="opc-block-summary opc-block-extras">
	<span class="title">Add Extras to this box</span>
	<p>Please Note: You may only include 1 bottle of wine or juice per box.</p>
	<div class="block items-in-cart" >
		<div class="content minicart-items">
			<div class="minicart-items-wrapper overflowed">
				<ol class="row minicart-items">
					<?php /*foreach($crossellProduct as $crossell): */?>
					<li class="col-md-4 col-sm-6" data-id="<?php /*echo $crossell["entity_id"] */?>">
						<div class="caddie-extra">
							<p>
								<img src="<?php /*echo $crossell["thumbnail"] */?>" alt="<?php /*echo $crossell["name"] */?>">
							</p>
							<span class="package-item-title"><?php /*echo $crossell["name"] */?></span>
							<div class="caddie-extra-cart">
								<div class="caddie-extra-cart-item extra-item"><input type="input" name="item-qty" value="<?php /*echo $crossell["qtyQuote"] */?>" id="item_<?php /*echo $crossell["entity_id"] */?>"></div>
								<div class="caddie-extra-cart-item btn-group">
									<button type="button" class="item-button decrease"><i class="fa fa-minus"></i></button>
									<button type="button" class="item-button increase"><i class="fa fa-plus"></i></button>
								</div>
								<div class="caddie-extra-cart-item caddie-extra-price">
									<span class="subtotal"><?php /*echo array_key_exists('special_price',$crossell) ? $priceHelper->currency($crossell["special_price"], true, false) : $priceHelper->currency($crossell["price"], true, false) */?></span>
								</div>
							</div>
						</div>
					</li>
					<?php /*endforeach; */?>
				</ol>
			</div>
		</div>
	</div>
</div>-->
<script type="text/x-magento-init">
	{
		"#extrasbox": {
			"Magento_Ui/js/core/app": {
			   "components": {
					"extrascomponent": {
						"component": "Infortis_Base/js/view/cart/totals",
						"template" : "Magento_Checkout/cart/totals"
					}
				}
			}
		}
	} 
</script>
<?php endif; ?>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>

