<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$itemsCount = $block->getQuote()->getItemsCount();
$itemsQty =  $block->getQuote()->getItemsQty();
?>

<?php if( !(($itemsCount == 1) && ($itemsQty == 1)) ): ?>
    <a class="action multicheckout" href="<?= /* @escapeNotVerified */ $block->getCheckoutUrl() ?>"><span><?= /* @escapeNotVerified */ __('Check Out with Multiple Addresses') ?></span></a>
<?php endif; ?>
