<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<p class="toolbar-amount" id="toolbar-amount">
    <?php if ($block->getLastPageNum() > 1): ?>
        <?php /* @escapeNotVerified */ echo __('Items %1-%2 of %3',
            '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
            '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
            '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
    <?php elseif ($block->getTotalNum() == 1): ?>
        <?php /* @escapeNotVerified */ echo __('%1 Item',
           '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
    <?php else: ?>
        <?php /* @escapeNotVerified */ echo __('%1 Items',
            '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
    <?php endif; ?>
</p>

<div class="toolbar-search">
    <div class="control">
        <input type="text" name="q" value="" placeholder="Search for hampers or gifts here" class="input-text" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off">
        <div id="search_autocomplete" class="search-autocomplete"></div>        
    </div>
    <div class="btn toolbar-search-button">SEARCH</div>    

</div>
