<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= /* @escapeNotVerified */ __('Sort listing by: ') ?></label>
    <div class="sorter-by-name slate">
        <select id="sorter-by" data-role="sorter" class="sorter-options">
            <option value="name" selected="selected">Name</option>
            <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>            
                <option value="<?= /* @escapeNotVerified */ $_key ?>"                
                </option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="sorter-by-name slate">
        <select id="sorter" data-role="sorter" class="sorter-options">
            <option value="price" selected="selected">Price</option>
            <option value="name">Name</option>
            <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>                
                <option value="<?= /* @escapeNotVerified */ $_key ?>"
                    <?php //if ($block->isOrderCurrent($_key)): ?>
                        
                    <?php //endif; ?>
                    >
                    <?php $block->escapeHtml(__($_order)) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?= /* @escapeNotVerified */ __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?= /* @escapeNotVerified */ __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?= /* @escapeNotVerified */ __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?= /* @escapeNotVerified */ __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?>
</div>
