<?php
/**
 * Blackbird EstimateTimeShipping Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_EstimateTimeShipping
 * @copyright       Copyright (c) 2018 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://store.bird.eu/license/
 * @support         help@bird.eu
 */
?>
<?php
/** @var \Magento\Catalog\Block\Product\View $block */
/** @var \Magento\Quote\Model\Quote\Item $item */
$item    = $block->getItem();
$itemId  = $item->getId();
$itemSku = $item->getSku();
?>
<?php if (!$this->helper('Blackbird\EstimateTimeShipping\Helper\Data')->getHowToDisplay()) : ?>
    <div id="preparation-time-<?= $itemId ?>" class="message edd-date">

    </div>
    <script type="text/x-magento-init">
    {
        "*": {
            "dateForm": {"divId": "#preparation-time-<?= $itemId ?>", "type": "item", "currentSku": "<?= $itemSku ?>"}
        }
    }

    </script>
<?php endif; ?>
