<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<h1>DONT MISS OUT!</h1>
<h5>EXCLUSIVE PRICING AND DEALS</h5>
<div class="newsletter">
    <form class="form subscribe" novalidate
          action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
          method="post"
          data-mage-init='{"validation": {"errorClass": "mage-error"}}'
          id="newsletter-validate-detail">
        <i class="fa fa-envelope-o "></i>
        <input name="email" type="email" class="form-control" id="newsletter"
               placeholder="<?php echo __('Your email address') ?>"
               data-validate="{required:true, 'validate-email':true}">

        <button class="btn btn-primary btn-subscribe" title="<?php echo __('Subscribe') ?>" type="submit">
            <span><?php echo __('Subscribe') ?></span>
        </button>
    </form>
</div>