<div class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-box">
                <ul>
                    <li>
                        <a href="#">MOTHER'S DAY HAMPERS</a>
                    </li>
                    <li>
                        <a href="#">GOURMET HAMPERS</a>
                    </li>
                    <li>
                        <a href="#">CHAMPAGNE AND WINE</a>
                    </li>
                    <li>
                        <a href="#">luxury hampers</a>
                    </li>
                    <li>
                        <a href="#">corporate gifts</a>
                    </li>
                    <li>
                        <a href="#">chocolate hampers</a>
                    </li>
                </ul>
            </div>
            <div class="footer-box">
                <ul>
                    <li>
                        <a href="#">GIFTS FOR HIM</a>
                    </li>
                    <li>
                        <a href="#"> GIFTS FOR HER</a>
                    </li>
                    <li>
                        <a href="#">GIFTS FOR TEACHERS</a>
                    </li>
                    <li>
                        <a href="#">JUST GIFTS</a>
                    </li>
                    <li>
                        <a href="#">best sellers</a>
                    </li>
                    <li>
                        <a href="#">add something extra</a>
                    </li>
                </ul>
            </div>
            <div class="footer-box">
                <ul>
                    <li>
                        <a href="#">BABY HAMPERS</a>
                    </li>
                    <li>
                        <a href="#">BABY BOY GIFTS</a>
                    </li>
                    <li>
                        <a href="#">BABY GIRL GIFTS</a>
                    </li>
                    <li>
                        <a href="#">LUXURY BABY GIFTS</a>
                    </li>
                    <li>
                        <a href="#">maternity baby gifts</a>
                    </li>
                    <li>
                        <a href="#">mother & baby hampers</a>
                    </li>
                </ul>
            </div>
            <div class="footer-box">
                <ul>
                    <li>
                        <a href="#">FATHER'S DAY GIFT HAMPERS</a>
                    </li>
                    <li>
                        <a href="#">BIRTHDAY HAMPERS</a>
                    </li>
                    <li>
                        <a href="#">ANNIVERSARY GIFTS</a>
                    </li>
                    <li>
                        <a href="#">housewarming hampers</a>
                    </li>
                    <li>
                        <a href="#">sympathy</a>
                    </li>
                    <li>
                        <a href="#">chinese new year</a>
                    </li>
                </ul>
            </div>
            <div class="footer-box">
                <ul>
                    <li>
                        <a href="#">VALENTINE'S DAY HAMPERS</a>
                    </li>
                    <li>
                        <a href="#">GIFT HAMPERS</a>
                    </li>
                    <li>
                        <a href="#">ALCOHOL-FREE MOTHER'S DAY gifts</a>
                    </li>
                </ul>
            </div>

        </div>

        <div class="row text-center">
            <div class="footer-social">
                <a class="social-icons" href="http://www.facebook.com/snowgoose.gift.boxes" target="_blank"><i
                        class="fa fa-facebook-square fa-2x" aria-hidden="true"></i></a>
                <a class="social-icons" href="http://www.facebook.com/snowgoose.gift.boxes" target="_blank"><i
                        class="fa fa-twitter fa-2x" aria-hidden="true"></i></a>
                <a class="social-icons" href="http://www.facebook.com/snowgoose.gift.boxes" target="_blank"><i
                        class="fa fa-instagram fa-2x" aria-hidden="true"></i></a>
                <a class="social-icons" href="http://www.facebook.com/snowgoose.gift.boxes" target="_blank"><i
                        class="fa fa-google-plus fa-2x" aria-hidden="true"></i></a>
                <a class="social-icons" href="http://www.facebook.com/snowgoose.gift.boxes" target="_blank"><i
                        class="fa fa-linkedin fa-2x" aria-hidden="true"></i></a>
            </div>

            <?php echo $block->getChildHtml('subscribe'); ?>

            <p class="partners">
                <a class="faw" href="#" target="_blank">
                    <img src="<?php echo $this->getViewFileUrl('images/footer-img3.png') ?>" alt="">
                </a>
                <a class="cherries" href="#" target="_blank">
                    <img src="<?php echo $this->getViewFileUrl('images/footer-img2.png') ?>" alt="">
                </a>
                <a class="cherries" href="#" target="_blank">
                    <img src="<?php echo $this->getViewFileUrl('images/footer-img1.png') ?>" alt="">
                </a>
                <a class="cherries" href="#" target="_blank">
                    <img src="<?php echo $this->getViewFileUrl('images/footer-img4.png') ?>" alt="">
                </a>
                <a class="cherries" href="#" target="_blank">
                    <img src="<?php echo $this->getViewFileUrl('images/footer-img5.png') ?>" alt="">
                </a>
            </p>
            <p>
                1300 132 663 &nbsp; | &nbsp; 3/2 Phillip Court, Port Melbourne, VIC 3207, D4 3-29 Birnie Avenue,
                Lidcombe, NSW 2141 &nbsp; | &nbsp;
                <a href="https://www.snowgoose.com.au/send-email">Send Email</a>
            </p>
            <div class="border-footer"></div>
            <p>
                <a href="#">FAQ'S&nbsp;</a>
                <a href="#">Delivery&nbsp;</a>
                <a href="#">Returns&nbsp;</a>
                <a href="#">Payment Methods&nbsp;</a>
                <a href="/about">About&nbsp;</a>
                <a href="#">Bockers & Pony&nbsp;</a>
                <a href="#">Gifting&nbsp;</a>
                <a href="#">Cost Transparency&nbsp;</a>
            </p>
        </div>
    </div>
    <div class="copy-right">
        <div class="container">
            <div style="padding: 20px 0px;">
                <span style="color: #ffffff"> © 2018 by Bockers & Pony. All rights reserved.</span>
                <p class="footer-bottom-icon1">
                    <a href="#">Privacy Policy</a>
                    &nbsp|&nbsp
                    <a href="#">Cookie Policy</a>
                    &nbsp|&nbsp
                    <a href="#">Terms & Conditions</a>
                    &nbsp|&nbsp
                    <a href="#">Site Map</a>
                </p>
            </div>
        </div>
    </div>
</div>