<?php
/**
 * Blackbird EstimateTimeShipping Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_EstimateTimeShipping
 * @copyright       Copyright (c) 2018 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://store.bird.eu/license/
 * @support         help@bird.eu
 */
?>
<?php $hours = $this->getHours(); ?>
<?php $minutes = $this->getMinutes(); ?>
<?php $entityHours = $this->getEntityHours(); ?>
<?php $entityMinutes = $this->getEntityMinutes(); ?>
<label class="admin__field-label" id="CutOfTimeSelect">
    <span><?php echo __('Cut Of Time'); ?></span>
</label>
<div class="admin__field-control">
    <select class="admin__control-select" name="cut_of_time_hours"
            data-form-part="estimatetimeshipping_preparationtimerule_form">
        <?php foreach ($hours as $val => $label): ?>
            <?php if ($val == $entityHours): ?>
                <option value="<?= $val ?>" selected><?= $label ?></option>
            <?php else: ?>
                <option value="<?= $val ?>"><?= $label ?></option>
            <?php endif; ?>
        <?php endforeach; ?>
    </select>
    :
    <select class="admin__control-select" name="cut_of_time_mins"
            data-form-part="estimatetimeshipping_preparationtimerule_form">
        <?php foreach ($minutes as $val => $label): ?>
            <?php if ($val == $entityMinutes): ?>
                <option value="<?= $val ?>" selected><?= $label ?></option>
            <?php else: ?>
                <option value="<?= $val ?>"><?= $label ?></option>
            <?php endif; ?>
        <?php endforeach; ?>
    </select>
    <div class="admin__field-note">
        <span><?php echo __('Time at which the order is prepared the next day') ?></span>
    </div>
</div>
<script>
    document.getElementById('CutOfTimeSelect').parentElement.classList.add('admin__field');
    document.getElementById('CutOfTimeSelect').parentElement.classList.add('_required');
</script>
