<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_MultiInventory
 */
?>
<?php

?>
<?php
/** @var $block \Amasty\MultiInventory\Block\Adminhtml\Warehouse\Lowstock\Grid */
$numColumns = sizeof($block->getColumns());
?>
<?php if ($block->getCollection()): ?>
    <?php if ($block->canDisplayContainer()): ?>
    <div id="<?php /* @escapeNotVerified */ echo $block->getId() ?>">
        <?php else: ?>
            <?php echo $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
        <?php endif; ?>

            <div class="admin__data-grid-header admin__data-grid-toolbar">
                <div class="admin__data-grid-header-row">
                    <?php $massActionAvailable = $block->getChildBlock('grid.massaction') && $block->getChildBlock('grid.massaction')->isAvailable() ?>
                        <div class="admin__filter-actions" data-role="filter-form" id="<?php /* @escapeNotVerified */ echo $block->getSuffixId('warehouses')?>">
                            <span class="field-row">
                                <label for="<?php /* @escapeNotVerified */ echo $block->getSuffixId('report_warehouse') ?>"
                                       class="admin__control-support-text">
                                    <span><?php /* @escapeNotVerified */ echo __('Select Warehouse') ?>:</span>
                                </label>
                              <select name="report_warehouse" id="<?php /* @escapeNotVerified */ echo $block->getSuffixId('report_warehouse')?>" class="admin__control-select">
                                    <?php foreach ($block->getWarehouses() as $_value => $_label): ?>
                                        <option value="<?php /* @escapeNotVerified */ echo $_value ?>" <?php if (is_array($block->getFilter('report_warehouse')) && in_array($_value, $block->getFilter('report_warehouse'))): ?> selected<?php endif; ?>><?php /* @escapeNotVerified */ echo $_label ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </span>

                        </div>
                    <?php if ($block->getChildBlock('grid.export')): ?>
                        <?php echo $block->getChildHtml('grid.export');?>
                    <?php endif; ?>
                </div>
                <div class="<?php if($massActionAvailable) { echo '_massaction ';} ?>admin__data-grid-header-row">
                    <?php if ($massActionAvailable): ?>
                        <?php echo $block->getChildHtml('grid.massaction') ?>
                    <?php else: ?>
                        <?php echo $block->getMainButtonsHtml() ? '<div class="admin__filter-actions">' . $block->getMainButtonsHtml() . '</div>' : ''; ?>
                    <?php endif; ?>
                    <?php $countRecords = $block->getCollection()->getSize(); ?>
                    <div class="admin__control-support-text">
                        <span id="<?php echo $block->escapeHtml($block->getHtmlId()) ?>-total-count" <?php /* @escapeNotVerified */ echo $block->getUiId('total-count') ?>>
                            <?php /* @escapeNotVerified */ echo $countRecords ?>
                        </span>
                        <?php /* @escapeNotVerified */ echo __('records found') ?>
                        <span id="<?php echo $block->escapeHtml($block->getHtmlId()) ?>_massaction-count"
                              class="mass-select-info _empty"><strong data-role="counter">0</strong> <span><?php /* @escapeNotVerified */ echo __('selected') ?></span></span>
                    </div>
                    <?php if ($block->getPagerVisibility()): ?>
                        <div class="admin__data-grid-pager-wrap">
                            <select name="<?php /* @escapeNotVerified */ echo $block->getVarNameLimit() ?>"
                                    id="<?php echo $block->escapeHtml($block->getHtmlId())?>_page-limit"
                                    onchange="<?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.loadByElement(this)" <?php /* @escapeNotVerified */ echo $block->getUiId('per-page') ?>
                                    class="admin__control-select">
                                <option value="20"<?php if ($block->getCollection()->getPageSize() == 20): ?>
                                    selected="selected"<?php endif; ?>>20
                                </option>
                                <option value="30"<?php if ($block->getCollection()->getPageSize() == 30): ?>
                                    selected="selected"<?php endif; ?>>30
                                </option>
                                <option value="50"<?php if ($block->getCollection()->getPageSize() == 50): ?>
                                    selected="selected"<?php endif; ?>>50
                                </option>
                                <option value="100"<?php if ($block->getCollection()->getPageSize() == 100): ?>
                                    selected="selected"<?php endif; ?>>100
                                </option>
                                <option value="200"<?php if ($block->getCollection()->getPageSize() == 200): ?>
                                    selected="selected"<?php endif; ?>>200
                                </option>
                            </select>
                            <label for="<?php echo $block->escapeHtml($block->getHtmlId())?>_page-limit"
                                   class="admin__control-support-text"><?php /* @escapeNotVerified */ echo __('per page') ?></label>
                            <div class="admin__data-grid-pager">
                                <?php $_curPage = $block->getCollection()->getCurPage() ?>
                                <?php $_lastPage = $block->getCollection()->getLastPageNumber() ?>

                                <?php if ($_curPage > 1): ?>
                                    <button class="action-previous"
                                            type="button"
                                            onclick="<?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.setPage('<?php /* @escapeNotVerified */ echo($_curPage - 1) ?>');return false;">
                                        <span><?php /* @escapeNotVerified */ echo __('Previous page') ?></span>
                                    </button>
                                <?php else: ?>
                                    <button type="button" class="action-previous disabled"><span><?php /* @escapeNotVerified */ echo __('Previous page') ?></span></button>
                                <?php endif; ?>

                                <input type="text"
                                       id="<?php echo $block->escapeHtml($block->getHtmlId())?>_page-current"
                                       name="<?php /* @escapeNotVerified */ echo $block->getVarNamePage() ?>"
                                       value="<?php /* @escapeNotVerified */ echo $_curPage ?>"
                                       class="admin__control-text"
                                       onkeypress="<?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.inputPage(event, '<?php /* @escapeNotVerified */ echo $_lastPage ?>')" <?php /* @escapeNotVerified */ echo $block->getUiId('current-page') ?> />

                                <label class="admin__control-support-text" for="<?php echo $block->escapeHtml($block->getHtmlId())
                                ?>_page-current">
                                    <?php /* @escapeNotVerified */ echo __('of %1', '<span>' . $block->getCollection()->getLastPageNumber() . '</span>') ?>
                                </label>
                                <?php if ($_curPage < $_lastPage): ?>
                                    <button title="<?php /* @escapeNotVerified */ echo __('Next page') ?>"
                                            class="action-next"
                                            onclick="<?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.setPage('<?php /* @escapeNotVerified */ echo($_curPage + 1) ?>');return false;">
                                        <span><?php /* @escapeNotVerified */ echo __('Next page') ?></span>
                                    </button>
                                <?php else: ?>
                                    <button type="button" class="action-next disabled"><span><?php /* @escapeNotVerified */ echo __('Next page') ?></span></button>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif ?>
                </div>
            </div>
        <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
            <table class="data-grid" id="<?php /* @escapeNotVerified */ echo $block->getId() ?>_table">
                <?php echo $block->getChildHtml('grid.columnSet'); ?>
            </table>
        </div>
    </div>
    <script>
        require([
            "jquery",
            "uiRegistry",
            "validation",
            "mage/mage",
            "mage/adminhtml/grid"
        ], function(jQuery, registry){

            <?php if ($block->getDependencyJsObject()): ?>
            registry.get('<?php /* @escapeNotVerified */ echo $block->getDependencyJsObject() ?>', function (<?php /* @escapeNotVerified */ echo $block->getDependencyJsObject() ?>) {
                <?php endif; ?>

            //<![CDATA[
            <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?> = new varienGrid('<?php /* @escapeNotVerified */ echo $block->getId() ?>', '<?php /* @escapeNotVerified */ echo $block->getGridUrl() ?>', '<?php /* @escapeNotVerified */ echo $block->getVarNamePage() ?>', '<?php /* @escapeNotVerified */ echo $block->getVarNameSort() ?>', '<?php /* @escapeNotVerified */ echo $block->getVarNameDir() ?>', '<?php /* @escapeNotVerified */ echo $block->getVarNameFilter() ?>');
            <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.useAjax = '<?php if ($block->getUseAjax()): /* @escapeNotVerified */ echo $block->getUseAjax(); endif; ?>';
                <?php if ($block->getRowClickCallback()): ?>
                <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.rowClickCallback = <?php /* @escapeNotVerified */ echo $block->getRowClickCallback() ?>;
                <?php endif; ?>
                <?php if ($block->getCheckboxCheckCallback()): ?>
                <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.checkboxCheckCallback = <?php /* @escapeNotVerified */ echo $block->getCheckboxCheckCallback() ?>;
                <?php endif; ?>
                <?php if ($block->getSortableUpdateCallback()): ?>
                <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.sortableUpdateCallback = <?php /* @escapeNotVerified */ echo $block->getSortableUpdateCallback()?>;
                <?php endif; ?>
                <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.bindSortable();
                <?php if ($block->getRowInitCallback()): ?>
                <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.initRowCallback = <?php /* @escapeNotVerified */ echo $block->getRowInitCallback() ?>;
                <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.initGridRows();
                <?php endif; ?>
                <?php if ($block->getChildBlock('grid.massaction') && $block->getChildBlock('grid.massaction')->isAvailable()): ?>
                <?php /* @escapeNotVerified */ echo $block->getChildBlock('grid.massaction')->getJavaScript() ?>
                <?php endif ?>
                <?php /* @escapeNotVerified */ echo $block->getAdditionalJavaScript(); ?>
            //]]>

        });
    </script>
<?php endif; ?>
