<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('ADD TO CART'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">	
    
      <?php if ($block->shouldRenderQuantity()): ?>
      <div class="field qty">
          <div class="control">
              <input type="number"
                     name="qty"
                     id="qty"
                     value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                     title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                     class="input-text qty"
                     data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                     />
          </div>
      </div>
      <?php endif; ?>
      <div class="actions">
          <button type="submit"
                  title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                  class="action tocart"
                  id="product-addtocart-button">
              <span><i class="fa fa-shopping-cart" aria-hidden="true"></i>&nbsp;<?= /* @escapeNotVerified */ $buttonTitle ?></span>
          </button>
      </div>

</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<?php endif; ?>
