<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$breadcrumbs = $objectManager->get('\Magento\Theme\Block\Html\Breadcrumbs');
$catalog = $objectManager->get('Magento\Catalog\Helper\Data');
$crumbs = $catalog->getBreadcrumbPath();
?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="breadcrumbs">
    <ul class="items">
		<li class="item home">
			<a href="<?php echo $this->getUrl() ?>" title="<?php echo __('Go to Home Page') ?>"><?php echo __('Home') ?></a>
		</li>
        <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
            <li class="item <?= /* @escapeNotVerified */ $crumbName ?>">
            <?php if (isset($crumbInfo['link'])) : ?>
                <a href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>" title="<?= $block->escapeHtml($crumbInfo['label']) ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>
            <?php else: ?>
                <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>