<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart\Grid */
?>

<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<button type="button" data-role="proceed-to-checkout" title="Go to Checkout" class="buy-now-btn">
    <span><i class="fa fa-lock" aria-hidden="true"></i>&nbsp;CHECKOUT NOW</span>
</button>
<li class="item"><a class="action multicheckout" href="http://magento2.com/multishipping/checkout/"><span>Check Out with Multiple Addresses</span></a></li>
<form action="<?= /* @escapeNotVerified */ $block->getUrl('checkout/cart/updatePost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'
          class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
	<div class="cart-content">
		<div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
			<?php if ($block->getPagerHtml()): ?>
				<div class="cart-products-toolbar cart-products-toolbar-top toolbar" data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?></div>
			<?php endif ?>
			<table id="shopping-cart-table"
				   class="cart items data table"
				   data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
				   "updateCartActionContainer": "#update_cart_action_container"}}'>
				<caption role="heading" aria-level="2" class="table-caption"><?= /* @escapeNotVerified */ __('Shopping Cart Items') ?></caption>
				<thead>
					<tr>
            <th class="col" scope="col"><span><?= /* @escapeNotVerified */ __(' ') ?></span></th>
						<th class="col item" scope="col"><span><?= /* @escapeNotVerified */ __('PRODUCT NAME') ?></span></th>
						<th class="col text-center" scope="col"><span><?= /* @escapeNotVerified */ __('QUANTITY') ?></span></th>
						<th class="col text-center" scope="col"><span><?= /* @escapeNotVerified */ __('UNIT PRICE') ?></span></th>
						<!--<th class="col subtotal" scope="col"><span><?=  __('Subtotal') ?></span></th> -->
						<th class="col action" scope="col">&nbsp;</th>
					</tr>
				</thead>
				<?php foreach ($block->getItems() as $_item): ?>
					<?= $block->getItemHtml($_item) ?>
				<?php endforeach ?>
			</table>
			<?php if ($block->getPagerHtml()): ?>
				<div class="cart-products-toolbar cart-products-toolbar-bottom toolbar" data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?></div>
			<?php endif ?>
		</div>
	</div>
    <div class="cart main actions">
		<!--
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                class="action clear" id="empty_cart_button">
            <span><?= /* @escapeNotVerified */ __('Clear Shopping Cart') ?></span>
        </button>
		-->
        <a class="button action shipping-cart-btn"
               href="#"
               title="edit card message(s)" style="float: left;">
                <span><i class="fa fa-pencil" aria-hidden="true"></i>&nbsp;&nbsp;<?= /* @escapeNotVerified */ __('Edit Card Message(s)') ?></span>
            </a>
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="button action shipping-cart-btn"
               href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
                <span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span>
            </a>
        <?php endif; ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $block->escapeHtml(__('Update My Changes')) ?>"
                class="action update shipping-cart-btn">
            <span><?= /* @escapeNotVerified */ __('Update My Changes') ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>

